### ISSUE TITLE
Easy navigation and responsive layout design

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#1]
**User story** 

When I first visit the website, I want a simple and easy to navigate website that is responsive, so that I can find important information about the gym quickly.

**Acceptance Criteria** 

- [x] Responsive on different devices.
- [x] Simple navigation so that the user can navigate without issue.

**Tasks**

- [x] Make navigation easy to use.
- [x] Make the website responsive on different devices with the help of bootstrap.
