### ISSUE TITLE
Classes page

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#10]
**User story:**
 As a member or potential member I would like to see what classes the gym offers. 

**Acceptance criteria** 

- [x] Classes section has a similar design to other pages. 
- [x] Responsive on different devices.
- [x] Information of the times and type the classes have.

**Tasks**

- [x] Reuse the layout from the membership page.
- [x] Add information about each class such as benefits, type and time.
- [x] Add images to the cards.
