### ISSUE TITLE
Contact page

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#2]
**User story**

As a gym member I would like to contact and get in touch with a personal trainer so that I can schedule a session.

**Acceptance Criteria** 

- [x] Contact page that gym members can contact personal trainers with a form.
- [x] Form is easy to use and responsive on all devices.

**Tasks**

- [x] Add a form on the contact page that is responsive on all devices.
- [x] Add a page to say their form is sent.
- [x] Form must be fully completed for the form to be sent.
