### ISSUE TITLE
Memberships

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#3]
**User story**

I would like to see the variety of memberships the gym offers and information on the benefits of the types.

**Acceptance criteria**

- [x] A list of the memberships types with information on price and benefits.

- [x] Memberships that has a appealing design and layout.

**Tasks**

- [x] Create a layout for the membership page that is responsive and visually appealing.
- [x] Add information about the memberships beneath each one as well as price.
