### ISSUE TITLE
Location, opening/close times

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#4]
**User story**

As a local resident I want to find the location of the gym as well as the opening and closing times.

**Acceptance criteria**

- [x] The location and opening times are added to the homepage but linked to the navbar on every page.

- [x] The section is easy to understand and visible with the right contrast.

- [x] Link it to the dropdown menu so that it takes them to the section.

**Tasks**

- [x] Ensure that it is visible in the footer/section and add a table to this information

- [x] The layout must be responsive on all devices.
