### ISSUE TITLE
Gallery section

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#5]
**User story**

As a client looking to purchase a membership, I would like to see pictures of the gym and the environment in which I could potentially be working out in. 

**Acceptance criteria** 

- [x] Build a gallery page that has a great layout and responsive.

**Tasks**

- [x] Add a gallery layout to a new page that links from the dropdown options.
- [x] Make sure the layout is responsive on each breakpoint.
