### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#6]
**User story**

As a user it would be useful if I could view the map of the place on the website.

**Acceptance criteria** 

- [x] Map is added in the footer or on a section of the page.

- [x] Map is responsive on different screens.

**Tasks**

- [x] Use Bootstrap or CSS to add the map.

- [x] Give it the right contrast so it doesn't blend in with background.
