### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by Ellis8462** [Ellis8462/Gym-website#8]
**User story**

 As a gym member I want to send feedback to the owners and employees on services, sessions and facility.

**Acceptance criteria**

- [x]  Feedback forum is on the contact page.
- [x] Make sure that everything is completed on the form before being sent.
- [x] Responsive on all devices.

**Tasks**

- [x]  Add a form to the contact page that has questions with radio buttons or checkboxes.
- [x]  Make sure the form is customized with using CSS.
- [x] Make sure the form has form validation with attributes like 'required'.
